Fix bug causing crash in create_user view
This change fixes the following error:

`TypeError: __json__() missing 1 required positional argument: 'request'`